spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    username: sa
    password: password
  h2:
    # http://localhost:8080/h2-console
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always